# Referencias bibliográficas {.unnumbered}

Álvarez, J., Sierra, J., Amaya, F., Herrera, J. e Hidalgo, D. (2022). *Validación experimental de un método analítico para el monitoreo de movimientos de tierra en masa mediante sensores de fibra óptica*. Ciencia e Ingeniería Neogranadina. Vol. 32 (2).

Aquae Fundación. (2022). *La escorrentía: un proceso clave en el ciclo del agua*.

Castañeda, I.E., Martínez, A.M. y Rómulo, M.V. (2023). *Antidesertización: sistemas urbanos de drenaje sostenible (SUDS) como gestión integral en la regulación y control de aguas de lluvias*. Pädi Boletín Científico de Ciencias Básicas e Ingenierías del ICBI. Vol. 11 (2023): Especial 3 (Noviembre).

Chen, S.S., Tsang, D.C.W., He, M., Sun, Y., Lau, L.S.Y., Leung, R.W.M., Lau, E.S.C., Hou, D., Liu, A. y Mohanty, S. (2021). *Designing sustainable drainage systems in subtropical cities: Challenges and opportunities*. Journal of Cleaner Production, 280, 124418.

Didactalia. (2011). *Reciclando todos ganamos*. Ciencias de la tierra y medio ambiente.

EIRD. (s.f.). *Inundaciones*. Teoría. ABC de desastres.

Extrategia Medios. (2019). *Zipaquirá comprometida con el cuidado del río Bogotá*.

Federación Nacional de Cafeteros. (2010). *Manejo de suelos y aguas para la prevención y mitigación de deslizamientos en fincas cafeteras*.

Freepik. (2024). *The Water Cycle*.

González, C. (2009). *Manejo y control de las aguas de escorrentía para mantener la calidad del agua*.

IDIGER. (2023). *Caracterización General del Escenario de Riesgo por Avenidas Torrenciales*.

IMPLAN Hermosillo. (2017). *Manual de lineamientos de diseño de infraestructura verde para municipios mexicanos*. Instituto Municipal de Planeación Urbana de Hermosillo. Blvd Luis Donaldo Colosio No. 248, Local 1 Colonia Prados del Centenario. C.P. 83260. Hermosillo, Sonora, México.

Lovado, J.S. (2013). *Retención de aguas lluvias a nivel predial para reducir picos y volúmenes de escorrentía*. Proyecto de grado Ingeniería Civil. Universidad de los Andes.

MASTERGIS. (2021). *Tipos de escorrentía*.

Ministerio de Vivienda Ciudad y Territorio. (2022). *Guía metodológica para la formulación e implementación de sistemas urbanos de drenaje sostenible*. Departamento Nacional De Planeación. Junio 30 de 2022.

NASA. (2014). *Megaflex solar array testing underway at plum rock*. AeroSpace Frontiers. Volume 16, issue 3.

NASA. (2023). *El ciclo del agua*. Administración Nacional de la Aeronaútica y del Espacio. Nov 30, 2023.

Parques Nacionales. (2023). *Dijeron sí: la historia de cómo las comunidades locales y Parques Nacionales Naturales de Colombia acordaron conservar las áreas protegidas*. Crónicas de los parques.

PNUD. (2022). *La escorrentía: un proceso clave en el Ciclo del Agua*. Programa de las Naciones Unidas para el Desarrollo.

Politécnico Grancolombiano. (2024). *Inició la reforestación de bosques y humedales en toda Colombia*.

Reynolds, J. y Stafford, D. (2002). *Do humans cause deserts?* In: Global Desertification. Dahlem Workshop Report 88, Dahlem University Press, Berlin.

Román, J. y González, E. (2014). *Buenas prácticas agrícolas para la reducción de la deriva y la escorrentía*.

Salazar, L.F. e Hincapié, E. (2010). *Manejo de suelos y aguas para la prevención y mitigación de deslizamientos en fincas cafeteras*. Avances Técnicos Cenicafe. 401(ISSN-0120-0178): 1–8.

Torres, P. (2019). *Limpieza de canales se hace con manejo especial: Pacaribe*. El Universal. Cartagena.

Valdivielso, A. (2017). *¿Qué son los SUDS?*
